import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Map from '../components/Map'
import Logo from '../components/header'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={styles.main}>
      <Logo/>
        <div className={styles.navtext}>
          <nav>
            <a href="https://www.translink.ca/">Home</a> |
            <a href="https://www.translink.ca/next-bus"> Bus</a> |
            <a href="https://www.translink.ca/transit-fares/pricing-and-fare-zones"> Price</a> |
            <a href="https://www.translink.ca/about-us/customer-service/contact-information"> Contact</a>
          </nav>
          <h1>Vancouver ExpoLine</h1>
        </div>
        <Map/>
        <div className={styles.footer}>
          <h1>Contact Information: 604-123-4567 Email:skytrain@gmail.com</h1>
        </div>
      </main>
    </>
  )
}
